spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?severTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:sql/schema-mysql.sql


mybatis:
  mapper-locations: ./mybatis/mapper/*.xml
  type-aliases-package: com.example.dormi.mapper.vo
  configuration:
    map-underscore-to-camel-case: true