DROP TABLE IF EXISTS point;
DROP TABLE IF EXISTS rule;
DROP TABLE IF EXISTS manager;
DROP TABLE IF EXISTS dormitory_student;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS dormitory;
DROP TABLE IF EXISTS student;
